CREATE TABLE D_RESSOURCE(
    ID_Ressource INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Unite_Energetique VARCHAR(255) NOT NULL,
    Valeur_Energetique FLOAT NULL,
    DT_Year DATE NOT NULL,
    FK_Type_Ressource INT NOT NULL,
    FK_Region INT NOT NULL,
    FK_Secteur_Energetique VARCHAR(255) NOT NULL,
    DELETE_LINE INT DEFAULT 0,
    DT_INSERT TIMESTAMP DEFAULT now(),
    DT_UPDATE TIMESTAMP DEFAULT now(),
    FOREIGN KEY (DT_Year) REFERENCES D_DATE(DT_Year),
    FOREIGN KEY (FK_Type_Ressource) REFERENCES D_TYPE_RESSOURCE(ID_Type_Ressource),
    FOREIGN KEY (FK_Region) REFERENCES D_REGION(ID_Region),
    FOREIGN KEY (FK_Secteur_Energetique) REFERENCES D_SECTEUR_ENERGETIQUE(Code_Secteur_Energetique)
);