CREATE TABLE D_SECTEUR_ENERGETIQUE(
    Code_Secteur_Energetique VARCHAR(255) PRIMARY KEY NOT NULL,
    Libelle VARCHAR(255) NOT NULL,
    DELETE_LINE INT DEFAULT 0,
    DT_INSERT TIMESTAMP DEFAULT now(),
    DT_UPDATE TIMESTAMP DEFAULT now()
);