CREATE TABLE D_TYPE_RESSOURCE(
    ID_Type_Ressource INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Libelle VARCHAR(255) NOT NULL,
    DELETE_LINE INT DEFAULT 0,
    DT_INSERT TIMESTAMP DEFAULT now(),
    DT_UPDATE TIMESTAMP DEFAULT now()
);