CREATE TABLE F_ENERGIE(

    DT_Year DATE NOT NULL,
    FK_Type_Ressource INT NOT NULL,
    FK_Region INT NOT NULL,
    FK_Secteur_Energetique INT NOT NULL,
    DELETE_LINE INT DEFAULT 0,
    DT_INSERT TIMESTAMP DEFAULT now(),
    DT_UPDATE TIMESTAMP DEFAULT now()
);